### ISSUE TITLE
Replace /css and /js directories with a single top-level directory

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#169]
The top level `/css` and `/js` directories which are copied from `themes/<theme>/css` and `themes/<theme>/js` may be unified to a single directory containing arbitrary sub-directories.

As a result, a theme only requires a directory like `themes/<theme>/assets`, which will be copied as a top-level directory `/assets`.

**Comment by dominikbraun** [comment]
The `css` and `js` directories need to be _deprecated_, not removed entirely.

**Comment by hmble** [comment]
Are you suggesting to add `AssetsDir` directory before `CSSir` and `JsDir`
https://github.com/verless/verless/blob/eae4531cfa867333b08ec9bc0fd95aaf61fc943c/core/create.go#L108-L109

Something like this

```diff
diff --git a/core/create.go b/core/create.go
index 97149cc..0271750 100644
--- a/core/create.go
+++ b/core/create.go
@@ -100,8 +100,8 @@ func CreateTheme(path, name string) error {
 
 	dirs := []string{
 		filepath.Join(path, ThemesDir, name, TemplateDir),
-		filepath.Join(path, ThemesDir, name, CSSDir),
-		filepath.Join(path, ThemesDir, name, JSDir),
+		filepath.Join(path, ThemesDir, name, AssetsDir, CSSDir),
+		filepath.Join(path, ThemesDir, name, AssetsDir, JSDir),
 	}
 
 	for _, dir := range dirs {
```

**Comment by dominikbraun** [comment]
So the original idea was to just support a single `assets` directory, instead of maintaining two directories in each template (`css` and `js`).

When _creating_ a new theme, we even may create `css` and `js` directories inside the new `assets` directory. But when it comes to _building_ a project, we just need to take care of the new `assets` directory (the content will be copied recursively anyway). So this ...

https://github.com/verless/verless/blob/0c80f6e30d01aaff6850c12ef7305e6900da79b9/writer/writer.go#L162-L171

 ... becomes just one single directory to be copied: `assets`.

**Comment by hmble** [comment]
hey @dominikbraun I changed the writer file as below.

```diff
    {
            src:      theme.CssDir(w.ctx.Path, w.ctx.Theme),
-           dest:     filepath.Join(w.ctx.OutputDir, config.CssDir),
+           dest:     filepath.Join(w.ctx.OutputDir, config.AssetsDir),
            fileOnly: true,
    },
    {
            src:      theme.JsDir(w.ctx.Path, w.ctx.Theme),
-           dest:     filepath.Join(w.ctx.OutputDir, config.JsDir),
+           dest:     filepath.Join(w.ctx.OutputDir, config.AssetsDir),
            fileOnly: true,
    },
```
After doing building example folder it copies css and js files to `assets` folder. Here's a tree structure of target folder.

```
target/
|-- about
|   `-- index.html
|-- assets
|   |-- index.js
|   `-- style.css
|-- atom.xml
|-- blog
|   |-- hidden
|   |   `-- index.html
|   |-- index.html
|   |-- making-barista-quality-espresso
|   |   `-- index.html
|   `-- steaming-milk-for-cappuccino
|       `-- index.html
|-- index.html
`-- static
    `-- img
        |-- cappuccino.jpg
        `-- espresso.jpg

8 directories, 11 files
```

Is this the final result you want ? Let me know if this is what you want, I will make PR.

**Comment by aligator** [comment]
@hmble I think dominik means also that the source theme directory should only have an assets folder and not an css and js folder.

So instead of this:
```
{
            src:      theme.CssDir(w.ctx.Path, w.ctx.Theme),
            dest:     filepath.Join(w.ctx.OutputDir, config.AssetsDir),
            fileOnly: true,
    },
    {
            src:      theme.JsDir(w.ctx.Path, w.ctx.Theme),
            dest:     filepath.Join(w.ctx.OutputDir, config.AssetsDir),
            fileOnly: true,
    },
```

we would only need one 
```
{
            src:      theme.AssetsDir(w.ctx.Path, w.ctx.Theme),
            dest:     filepath.Join(w.ctx.OutputDir, config.AssetsDir),
            fileOnly: true,
    },
```

@dominikbraun The bad thing about this is that we need to change the structure of themes -> breaking change.
The good thing is that the assets folder could be used for anything, even pictures and so on.

Also we may have to consider how to handle the generated folder. Currently it would be an extra folder besides assets.
I think this would be ok for now as it should be on it's own.

**Comment by dominikbraun** [comment]
@aligator Right, the thing that needs to be done here basically is replacing this entry:

```go
 { 
 	src:      theme.CssDir(w.ctx.Path, w.ctx.Theme), 
 	dest:     filepath.Join(w.ctx.OutputDir, config.CssDir), 
 	fileOnly: true, 
 },
```

With something like:

```go
 { 
 	src:         theme.AssetsDir(w.ctx.Path, w.ctx.Theme), 
 	dest:       filepath.Join(w.ctx.OutputDir, config.AssetsDir), 
 	fileOnly: true,
 },
```

And delete the other entry for `js`, so that we simply replace `css` and `js` with `assets`- that's it.

> The bad thing about this is that we need to change the structure of themes -> breaking change.

Not necessarily: If @hmble doesn't _replace_ `css` and `js` with `assets` and just _adds_ `assets`, we still support the `css` and `js` directories and can deprecate them. That means we recommend to use `assets` and finally remove `css` and `js` in the next major version.

**Comment by hmble** [comment]
So should I keep `CssDir` and `JsDir` or remove them ?

**Comment by dominikbraun** [comment]
Keep them. They'll be removed in the next major release instead.

**Comment by dominikbraun** [comment]
Done with #193.
