### ISSUE TITLE
Create default .gitignore files within new project

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#176]
A new project can be created using `verless create project <name>`. This freshly created, fully initialized standard project should contain a `.gitignore` file by default:

```
# File: .gitignore
generated/
```

The contents of this file can be stored in `core/defaults.go` and created along with the other files in `core.CreateProject`.

**Comment by hmble** [comment]
What should we include in `.gitignore` file ? or create just an empty file ?

**Comment by dominikbraun** [comment]
There should be at least one entry: `generated/`. The reason is simple:

#160 introduce pre-build commands you can use for generating any files you want, and #166 will introduce pre-build commands for themes you can use to generate CSS. Those generated file should be stored inside a directory called `generated` - we support a `generated` directory in the project root and a `generated` directory in each theme's directory.

**Comment by dominikbraun** [comment]
Fixed with #179.
