### ISSUE TITLE
Add emojis to style package

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#196]
The file [`out/style/style.go`](https://github.com/verless/verless/blob/master/out/style/style.go) needs some more emojis. Each emoji is a constant whose name is the GitHub name of that emoji, and the value is the emoji itself. These emojis should be added:

| Name | Emoji |
|--------|-------|
|Fire|https://emojipedia.org/fire/|
|Sparkles|https://emojipedia.org/sparkles/|
|Exclamation|https://emojipedia.org/exclamation-mark/|
|Bulb|https://emojipedia.org/light-bulb/|
|X|https://emojipedia.org/cross-mark/|
|HeavyCheckMark|https://emojipedia.org/check-mark/|
|Warning|https://emojipedia.org/warning/|

`Name` is the constant's name and `Emoji` is the Emojipedia URL where the emoji can be copied from:

1. Copy the emoji from Emojipedia: 
![image](https://user-images.githubusercontent.com/36575275/95245194-14206400-0813-11eb-8e99-70f38f9492a8.png)
2. Add the constant:
```go
Fire = "🔥"
```

**Comment by rperry99** [comment]
Hey @dominikbraun  I can take care of this for you.
