### ISSUE TITLE
Move core.loadPlugins function into plugin package

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#210]
In `core/build.go`, there's a small function called `loadPlugins`. This function returns a simple map containing all plugin keys and a corresponding function that loads the plugin - i.e. it simply returns an instance.

https://github.com/verless/verless/blob/16673b1223f95b7a4033a3caafa5cbedf68e9d0b/core/build.go#L301-L311

I have no idea why this function is inside the `core` package. It should be inside the `plugin` package. The best way would be to just move it into a new file `plugin/plugin.go`. The function signature can remain unchanged.

**Comment by ananichev** [comment]
Hey @dominikbraun, I'll take this one

**Comment by ananichev** [comment]
@dominikbraun, could you please review PR https://github.com/verless/verless/pull/211
