### ISSUE TITLE
Grammar in plugin subsection of the Tutorial

### ISSUE THREAD

**Issue by YusefTech** [verless/verless#221]
### Description

In the tutorial Subsection you have:
"verless supports some plugins that are desirable for many, but not all project out there - so verless wants you to explicitly **active** the plugins you need. Maybe you noticed that small plugins section in verless.yml:"

### Reproduce

1. Go to this link: https://github.com/verless/verless/blob/master/docs/create-a-website-using-verless.md
2. Scroll down to "Plugins" Subsection

### Expected behavior

I'm pretty sure you mean to say:
"... so verless wants you to explicitly **make active (or) activate** the plugins you need. ..."

### verless version

The output of `verless version`:
v0.5.0 

### System information

* OS: [Windows]
* Version: [e.g. 10]

**Comment by panvicka** [comment]
Hello,
Can you please assign this task to me?
Thank You

**Comment by aligator** [comment]
Thanks!
