### ISSUE TITLE
Structure of /assets directory should be preserved on copy

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#225]
### Description

Each theme has an `assets` directory. When building the site, the `assets` directory of the active theme will be copied to the project root, making it available as `/assets` in the HTML.

Unfortunately, verless only copies the files but doesn't preserve the directory structure: `assets/css/style.css` will be copied as `/assets/style.css` instead of `/assets/css/style.css`.

IMO, this is because `fileOnly` is set to `true` - which makes `fs.CopyFromOS` only copy the file in the target directory `/assets`, without preserving the directory structure.

https://github.com/verless/verless/blob/d370ee33bfd9bb9b1c7f01890d0b82589a213bf8/writer/writer.go#L180-L184

I think this could be fixed by simply removing `fileOnly: true`.

**Verify if the fix works**

To test if a fix works, create a CSS file `themes/default/assets/css/test.css` in the `example` project, run `verless serve example` and check if `localhost:8080/assets/css/test.css` exists.

**Comment by mo3taz1705** [comment]
@dominikbraun I would like to do it. can you assign it to me ?

**Comment by dominikbraun** [comment]
Fixed with #227.
