### ISSUE TITLE
Implement verless create file command

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#65]
There should be a command like `verless create file my-blog-post.md` to create an initialized Markdown file.

**Comment by hmble** [comment]
I have few questions about behaviour of this command.

1. Do you want to create a file with some default frontmatter for example
```
---
Title:
Description:
Date: 2020-10-02
---
```
2. Should file be created in `content` folder under current directory or with custom path under current directory ?

**Comment by dominikbraun** [comment]
1. Yes, the `verless create file` command should safe some time for the user, so that he doesn't have to manually create the Front Matter.
2. I'd suggest to directly create it within the `content` directory.

**Comment by dominikbraun** [comment]
Fixed with #182, thanks!
